### ISSUE TITLE
Enable DynamoDB Streams

### ISSUE THREAD

**Issue by brianm** [srijs/rust-aws-lambda#41]
It looks like dynamodb events are blacklisted -- I would like to use this library to process dynamodb streams events.

**Comment by Keshi** [comment]
Darn, I was wanting to use this library for that too.

**Comment by LegNeato** [comment]
I'll take a look. It's mainly blacklisted because the code generation isn't quite right for it yet. Feel free to send a PR if I don't get to it in time. You could also just create your own struct manually with the shape you want in the meantime. As long as it implements Deserialize you are good to go

**Comment by LegNeato** [comment]
The events crate has now moved to https://github.com/LegNeato/aws-lambda-events. Because of GitHub limitations (https://help.github.com/articles/transferring-an-issue-to-another-repository/) this issue is being closed rather than transferred.

If it is still relevant, please open an issue in the [new repo](https://github.com/LegNeato/aws-lambda-events).

Sorry for the churn!
