### ISSUE TITLE
Support Go Embedded Fields

### ISSUE THREAD

**Issue by ant1441** [srijs/rust-aws-lambda#44]
The Cognito event definitions have two structs which have an embedded field (`CognitoEventUserPoolsHeader`):
* `CognitoEventUserPoolsPreSignup`
* `CognitoEventUserPoolsPostConfirmation`

[cognito.go#L25](https://github.com/aws/aws-lambda-go/blob/fb8f88d824489a878aee1e0badde7d8e129f8767/events/cognito.go#L25)

It appears as though the pest grammar does not support this.

I think the Rust structs would end up looking something like:

```
#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub struct CognitoEventUserPoolsPreSignup {
    #[serde(flatten)]
    pub header: CognitoEventUserPoolsHeader,
    pub request: CognitoEventUserPoolsPreSignupRequest,
    pub response: CognitoEventUserPoolsPreSignupResponse,
}
```

It would be great if support could be added for this, thanks.

**Comment by LegNeato** [comment]
The events crate has now moved to https://github.com/LegNeato/aws-lambda-events. Because of GitHub limitations (https://help.github.com/articles/transferring-an-issue-to-another-repository/) this issue is being closed rather than transferred.

If it is still relevant, please open an issue in the [new repo](https://github.com/LegNeato/aws-lambda-events).

Sorry for the churn!
